timezone: 'Asia/Shanghai'

  # Site settings
site_name : Hector的博客
title: Hector的博客
email: hhqcontinue@gmail.com
description: Hector's blog
  Power by Hector
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.aintnot.com" # the base hostname & protocol for your site
github_username:  hhqcontinue
keywords: "ainnot, Hector的博客"
paginate: 10
paginate_path: "page:num"

  # Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title

gems:
  - jekyll-sitemap
  - jekyll-paginate
