timezone: 'Asia/Shanghai'

  # Site settings
site_name : Blog - hoohack
email: hhqcontinue@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.hoohack.me" # the base hostname & protocol for your site
github_username:  hhqcontinue
keywords: "hoohack, hoohack的博客"
paginate: 10
paginate_path: "page:num"

  # Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title

plugins: 
    - jekyll-sitemap
    - jekyll-paginate
