timezone: 'Asia/Shanghai'

# Site settings
site_name : Hector's blog
title: 我并非不是一个菜鸟
email: hhqcontinue@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Power by Hector
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.aintnot.com" # the base hostname & protocol for your site
github_username:  hhqcontinue

paginate: 10

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title